### ISSUE TITLE
Download count not incrementing

### ISSUE THREAD

**Issue by jon--lee** [aclark4life/vanity#18]
Hi,
I noticed a few days ago that download counts weren't incrementing anymore. I ran
```
$ vanity django
```
twice with about a day in between and got the same download count (`17,560,592`). It seemed suspicious that no one would download Django in that time period. I tried using PyPIXmlRpc on its own and also found that the download count was the same and hadn't incremented. Maybe this is an issue at PyPI?

Thanks

**Comment by aclark4life** [comment]
Confirmed, maybe @dstufft knows something. Thanks for reporting

**Comment by pooya-eghbali** [comment]
PyPI had a database migration on Aug 15, 2015 and pypi.python.org was down. I noticed this issue (download count not increment) from the day after the database migration. It is probably an issue at PyPI.

**Comment by dstufft** [comment]
Should be fixed now I think.

**Comment by aclark4life** [comment]
Yep, thanks
```
$ vanity -q django
Django has been downloaded 17,562,306 times!
```

**Comment by jon--lee** [comment]
I think it's frozen again.
```
$ vanity -q django
Django has been downloaded 17,626,069 times!
```
It's been saying that for three days now.
@dstufft how was it fixed previously?

**Comment by madmat3001** [comment]
It's frozen for me again, since about the beginning of february...

**Comment by aclark4life** [comment]
@madmat3001 Yep, this is almost certainly a PyPI issue. Probably best to open a ticket here: https://bitbucket.org/pypa/pypi/issues CC: @dstufft
