### ISSUE TITLE
Removing "bot download" from counts

### ISSUE THREAD

**Issue by kootenpv** [aclark4life/vanity#19]
What does this do about the fact that PyPi is being crawled very often? It would be great if we could get a better estimate of "actual" counts, or did you do something to account for the number of bots out there?

**Comment by aclark4life** [comment]
Nothing and nope; what do you suggest we do to account for "bot download"?

**Comment by kootenpv** [comment]
Perhaps what is possible is to script uploading a nonsense unguessable package name to `pip`; every day a new update.

I guess from that we can estimate the number of bots active, say, given a week.

After some weeks/months of data, you can try to model a prediction backwards, and could correct the numbers.

Perhaps someone can think of a better approach.

**Comment by aclark4life** [comment]
Let's assume the fix for this is for vanity to query the dataset mentioned here, instead of relying on PyPI: https://mail.python.org/pipermail/distutils-sig/2016-May/028986.html, now tracking that in #22 .
