### ISSUE TITLE
Enable Travis CI for this repo

### ISSUE THREAD

**Issue by hugovk** [aclark4life/vanity#31]
@aclark4life Please can you enable Travis CI for your aclark4life/vanity repo? 

That would pick up some recent build problems when PRs are submitted for merge, and before they're merged.

Enable it here: https://travis-ci.org/profile

**Comment by aclark4life** [comment]
Done! Thanks

![screenshot 2016-10-08 06 21 36](https://cloud.githubusercontent.com/assets/72164/19212457/7b9ad0c0-8d1f-11e6-9af1-48d8e6751243.png)
