### ISSUE TITLE
Enable Coveralls for this repo

### ISSUE THREAD

**Issue by hugovk** [aclark4life/vanity#36]
Now we're adding more tests, it'd be great to track coverage too. The existing test are ready to use it.

@aclark4life Please could you enable coveralls.io for this repo? https://coveralls.io/repos/new

**Comment by mattjegan** [comment]
@hugovk @aclark4life And to stay on top of style perhaps [landscape.io](https://landscape.io/)? 

An example from one of my repos: https://landscape.io/github/mattjegan/rancat/31

**Comment by hugovk** [comment]
I've added Landscape: https://landscape.io/github/aclark4life/vanity

**Comment by killVung** [comment]
How about just using the coverage package from Python?
I heard it's pretty solid...

Sometimes Keep It Simple Stupid is better than making it really complex at the beginning

**Comment by hugovk** [comment]
@killVung The coverage package is already being used to generate the coverage. Coveralls is just an place to keep track of the coverage over builds, and easier to check than having to dig into Travis CI logs: https://travis-ci.org/aclark4life/vanity/jobs/166537108#L1336

Here's how it looks for my fork: https://coveralls.io/github/hugovk/vanity

**Comment by hugovk** [comment]
Oh, looks like I do have permission to enable Coveralls for this repo, so here we go!

https://coveralls.io/github/aclark4life/vanity

**Comment by killVung** [comment]
I see sorry about lacking of observation

**Comment by hugovk** [comment]
Should another option be set for Landscape to check PRs?

![image](https://cloud.githubusercontent.com/assets/1324225/19354090/40d3a5c2-916e-11e6-8e0f-255859b28e4d.png)

**Comment by mattjegan** [comment]
@hugovk Perhaps fail if errors are found? If the score decreases I wouldn't be too worried since landscape is very pedantic

**Comment by hugovk** [comment]
Thanks, let's see how this goes:

![image](https://cloud.githubusercontent.com/assets/1324225/19377127/427e7c3e-91ec-11e6-8a74-b138871a2f50.png)
