### ISSUE TITLE
Add function docstrings

### ISSUE THREAD

**Issue by hugovk** [aclark4life/vanity#39]
Some of the functions in [vanity.py](https://github.com/aclark4life/vanity/blob/master/vanity.py) have empty docstrings, for example:

```python
def normalize(name):
    """
    """
    http = HTTPSConnection(PYPI_HOST)
    http.request('HEAD', '/pypi/%s/' % name)
    r = http.getresponse()
    if r.status not in (200, 301):
        raise ValueError(r.reason)
    return r.getheader('location', name).split('/')[-1]
```

It would be great to fill these in.

More info on docstrings:
 * http://www.pythonforbeginners.com/basics/python-docstrings
 * https://www.python.org/dev/peps/pep-0257/

**Comment by masterp4dev** [comment]
Hi @hugovk, I am jumping on this. Thanks

**Comment by darthbhyrava** [comment]
Hello @masterp4dev,

Sorry for the PR, I'd already started working on this. Please feel free to submit your own PR, it is entirely possible your changes might be more suited to @hugovk 's needs. :)

**Comment by masterp4dev** [comment]
It's fine @darthbhyrava 🙌
