### ISSUE TITLE
Fix TODO: refactor normalize when given empty string

### ISSUE THREAD

**Issue by hugovk** [aclark4life/vanity#51]
[`test_empty`](https://github.com/aclark4life/vanity/blob/master/tests.py) has a TODO that needs fixing:

```python
    def test_empty(self):
        """
        TODO: this test is rather slow to run,
        perhaps normalize could be refactored to check this
        and kick out faster.
        """
        normalized = vanity.normalize("")
        self.assertEqual(normalized, "")
```

So right now [`normalize`](https://github.com/aclark4life/vanity/blob/master/vanity.py) is looking up on PyPI for a package called "" and not finding it. The empty string is a special case; there's no point looking for anything so it'd make more sense to validate and to return something sensible right away.

**Comment by M3rs** [comment]
That test shows that the PyPI search for "" is returning "". Could this be handled with just an if statement?

```
def normalize(name):
    # (docstring omitted)
    if name == "":
        return ""

    # ...other code
    return normalize_name
```

**Comment by hugovk** [comment]
Yes, that's one way.

**Comment by M3rs** [comment]
Would that be okay - Do you want me to work this into PR #50 ?

**Comment by hugovk** [comment]
Yes, that'd be okay, but put it in another PR: it's better to keep distinct things in each PR, it makes them easier to discuss and in general the simpler ones can get merged quicker.

**Comment by M3rs** [comment]
Good point, created PR #52 (also fix the test class name / remove the TODO)
